ekf_filter_node:
  ros__parameters:
    frequency: 50.0
    sensor_timeout: 0.2
    two_d_mode: true

    # ① 주 오도메트리로 RF2O를 사용
    odom0: /odom_rf2o           # RF2O가 퍼블리시하는 odom 토픽
    odom0_config: [ 
      true,  true,  false,      # x,y position ON
      false, false, true,       # yaw ON
      true,  true,  false,      # vx,vy ON
      false, false, true,       # yaw rate ON
      false, false, false       # accel OFF
    ]
    odom0_differential: false
    odom0_queue_size: 5

    #② 보조로 IMU는 yaw 보정만
    imu0: /imu/data
    imu0_config: [
      false, false, false,
      false, false, true,
      false, false, false,
      false, false, true,
      true, true, false
    ]
    imu0_remove_gravitational_acceleration: true

    map_frame: map
    odom_frame: odom
    base_link_frame: base_footprint
    world_frame: odom
    publish_tf: true
