slam_toolbox:
  ros__parameters:
    use_sim_time: true
    resolution: 0.05
    map_update_interval: 2.0
    scan_topic: /scan
    odom_frame: odom
    base_frame: base_footprint
    map_frame: map
    enable_interactive_mode: false
    minimum_travel_distance: 0.2
    minimum_travel_heading: 0.1
    max_laser_range: 15.0
    loop_closure_enabled: true
